### ISSUE TITLE
Sprites for Trees and Bushes

### ISSUE THREAD

**Issue by hedy-99** [Strawbatz/Bat_Brewery#22]
- [x] Leaf trees
- [x] Pine trees
- [x] Bushes
- [x] Rock 1
- [x] Rock 2

**Comment by EmilEkroth** [comment]
- [ ] Oaks
- [ ] Pines
- [ ] Spruce
- [ ] Birch
- [ ] Stones
- [ ] Small bush
- [ ] Large bush
- [ ] Shrubbs
